apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: terrascan-pipeline-task
spec:
  steps:
    - name: terrascan-pipeline-step
      image: accurics/terrascan:latest
      command: ["/bin/sh","-c"]
      args:
       - >
        /go/bin/terrascan scan -r git -u https://github.com/sangam14/terrascan-argocd.git -i k8s -t k8s 
